# Use case:
# * user has some indices in Elasticsearch
# * user has two tables in Hydrolix named `siem` and `logs`
#
#  User wants to see those two Hydrolix tables as Elasticsearch indices in Kibana
#  User wants to see all their Elasticsearch indices in Kibana as they were before
#
#  ( ingest is not the case here, but the config has to be present due to impl. constraints )

logging:
  level: info
frontendConnectors:
  - name: elastic-ingest
    type: elasticsearch-fe-ingest
    config:
      listenPort: 8080
  - name: elastic-query
    type: elasticsearch-fe-query
    config:
      listenPort: 8080
backendConnectors:
  - name: my-minimal-elasticsearch
    type: elasticsearch
    config:
      url: "http://elasticsearch:9200"
      user: elastic
      password: quesmaquesma
  - name: my-hydrolix-instance
    type: hydrolix
    config:
      url: "clickhouse://localhost:9000"
      user: "u"
      password: "p"
      database: "d"
ingestStatistics: true
processors:
  - name: my-query-processor
    type: quesma-v1-processor-query
    config:
      indexes:
        siem:
          target:
            - my-hydrolix-instance
        logs:
          target:
            - my-hydrolix-instance
        "*":
          target:
            - my-minimal-elasticsearch
pipelines:
  - name: my-elasticsearch-proxy-read
    frontendConnectors: [ elastic-query ]
    processors: [ my-query-processor ]
    backendConnectors: [ my-minimal-elasticsearch, my-hydrolix-instance ]
